import { defineConfig, devices } from '@playwright/test';
import { env } from '@/utils/env';
import { allureCategories, allureEnvironmentInfo } from '@/config/allure.config';
import { STORAGE_STATE_PATH, TIMEOUTS } from '@/config/constants';

const isCI = env.CI;

const allureReporter = [
  'allure-playwright',
  {
    resultsDir: 'allure-results',
    detail: true,
    suiteTitle: true,
    environmentInfo: allureEnvironmentInfo,
    categories: allureCategories,
  },
] as const;

/**
 * Playwright config. Per Constitution:
 *   C1 — retain-on-failure for trace/screenshot/video; no implicit timeouts.
 *   C2 — auth state generated by `setup` project, never committed.
 *   C6 — observability: trace + screenshot + video on failure; Allure feeds
 *        from both local and CI runs. CI also gets the GitHub reporter.
 */
export default defineConfig({
  testDir: './tests',
  fullyParallel: true,
  forbidOnly: isCI,
  retries: isCI ? 2 : 0,
  // Conditional spread keeps prop absent locally (exactOptionalPropertyTypes).
  ...(isCI ? { workers: 2 } : {}),
  timeout: TIMEOUTS.test,
  expect: {
    timeout: TIMEOUTS.expect,
  },
  reporter: isCI
    ? [
        ['list'],
        ['github'],
        ['html', { open: 'never', outputFolder: 'playwright-report' }],
        allureReporter,
      ]
    : [['list'], ['html', { open: 'never', outputFolder: 'playwright-report' }], allureReporter],
  outputDir: './test-results',
  use: {
    baseURL: env.BASE_URL,
    trace: 'retain-on-failure',
    screenshot: 'only-on-failure',
    video: 'retain-on-failure',
    actionTimeout: TIMEOUTS.action,
    navigationTimeout: TIMEOUTS.navigation,
    testIdAttribute: 'data-test',
  },
  projects: [
    {
      name: 'setup',
      testMatch: /.*\.setup\.ts$/,
    },
    {
      name: 'api',
      testDir: './tests/api',
      use: {
        baseURL: env.API_URL,
      },
    },
    {
      name: 'ui-chromium',
      use: {
        ...devices['Desktop Chrome'],
        storageState: STORAGE_STATE_PATH,
      },
      dependencies: ['setup'],
      testIgnore: ['**/api/**', '**/*.setup.ts'],
    },
    {
      name: 'ui-firefox',
      use: {
        ...devices['Desktop Firefox'],
        storageState: STORAGE_STATE_PATH,
      },
      dependencies: ['setup'],
      testIgnore: ['**/api/**', '**/*.setup.ts'],
    },
    {
      name: 'ui-webkit',
      use: {
        ...devices['Desktop Safari'],
        storageState: STORAGE_STATE_PATH,
      },
      dependencies: ['setup'],
      testIgnore: ['**/api/**', '**/*.setup.ts'],
    },
  ],
});
